/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\readBuddySepiaTheme.ts
 * Command: astryx theme build src\theme\readBuddySepiaTheme.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./read-buddy-sepia.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const readBuddySepiaTheme: DefinedTheme;
